project_id = "ggxuemuasudnlyhhxkbu"

[functions.generate-ebook]
verify_jwt = true

[functions.generate-sales-page]
verify_jwt = true

[functions.assistant-chat]
verify_jwt = true

[functions.improve-copy]
verify_jwt = true

[functions.generate-presell]
verify_jwt = true

[functions.generate-sales-page-from-prompt]
verify_jwt = true
