/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthenticatedSalesPagesRouteImport } from './routes/_authenticated/sales-pages'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNewEbookRouteImport } from './routes/_authenticated/new-ebook'
import { Route as AuthenticatedEbooksRouteImport } from './routes/_authenticated/ebooks'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedEbooksIdRouteImport } from './routes/_authenticated/ebooks.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesPagesRoute = AuthenticatedSalesPagesRouteImport.update({
  id: '/sales-pages',
  path: '/sales-pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewEbookRoute = AuthenticatedNewEbookRouteImport.update({
  id: '/new-ebook',
  path: '/new-ebook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEbooksRoute = AuthenticatedEbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEbooksIdRoute = AuthenticatedEbooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEbooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ebooks': typeof AuthenticatedEbooksRouteWithChildren
  '/new-ebook': typeof AuthenticatedNewEbookRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sales-pages': typeof AuthenticatedSalesPagesRoute
  '/p/$slug': typeof PSlugRoute
  '/ebooks/$id': typeof AuthenticatedEbooksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ebooks': typeof AuthenticatedEbooksRouteWithChildren
  '/new-ebook': typeof AuthenticatedNewEbookRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sales-pages': typeof AuthenticatedSalesPagesRoute
  '/p/$slug': typeof PSlugRoute
  '/ebooks/$id': typeof AuthenticatedEbooksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ebooks': typeof AuthenticatedEbooksRouteWithChildren
  '/_authenticated/new-ebook': typeof AuthenticatedNewEbookRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sales-pages': typeof AuthenticatedSalesPagesRoute
  '/p/$slug': typeof PSlugRoute
  '/_authenticated/ebooks/$id': typeof AuthenticatedEbooksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/assistant'
    | '/dashboard'
    | '/ebooks'
    | '/new-ebook'
    | '/profile'
    | '/sales-pages'
    | '/p/$slug'
    | '/ebooks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/assistant'
    | '/dashboard'
    | '/ebooks'
    | '/new-ebook'
    | '/profile'
    | '/sales-pages'
    | '/p/$slug'
    | '/ebooks/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/assistant'
    | '/_authenticated/dashboard'
    | '/_authenticated/ebooks'
    | '/_authenticated/new-ebook'
    | '/_authenticated/profile'
    | '/_authenticated/sales-pages'
    | '/p/$slug'
    | '/_authenticated/ebooks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales-pages': {
      id: '/_authenticated/sales-pages'
      path: '/sales-pages'
      fullPath: '/sales-pages'
      preLoaderRoute: typeof AuthenticatedSalesPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-ebook': {
      id: '/_authenticated/new-ebook'
      path: '/new-ebook'
      fullPath: '/new-ebook'
      preLoaderRoute: typeof AuthenticatedNewEbookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebooks': {
      id: '/_authenticated/ebooks'
      path: '/ebooks'
      fullPath: '/ebooks'
      preLoaderRoute: typeof AuthenticatedEbooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebooks/$id': {
      id: '/_authenticated/ebooks/$id'
      path: '/$id'
      fullPath: '/ebooks/$id'
      preLoaderRoute: typeof AuthenticatedEbooksIdRouteImport
      parentRoute: typeof AuthenticatedEbooksRoute
    }
  }
}

interface AuthenticatedEbooksRouteChildren {
  AuthenticatedEbooksIdRoute: typeof AuthenticatedEbooksIdRoute
}

const AuthenticatedEbooksRouteChildren: AuthenticatedEbooksRouteChildren = {
  AuthenticatedEbooksIdRoute: AuthenticatedEbooksIdRoute,
}

const AuthenticatedEbooksRouteWithChildren =
  AuthenticatedEbooksRoute._addFileChildren(AuthenticatedEbooksRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEbooksRoute: typeof AuthenticatedEbooksRouteWithChildren
  AuthenticatedNewEbookRoute: typeof AuthenticatedNewEbookRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSalesPagesRoute: typeof AuthenticatedSalesPagesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEbooksRoute: AuthenticatedEbooksRouteWithChildren,
  AuthenticatedNewEbookRoute: AuthenticatedNewEbookRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSalesPagesRoute: AuthenticatedSalesPagesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
